import Foundation

class managerSistem {
    var explicar: [Projeto] = [
        
        //Projeto(titulo: "", informacao: "", ilustrativo: "")
        //SOL
Projeto(titulo: "Sol", informacao: "O Sol é uma estrela situada no centro do nosso sistema solar. Sua gravidade mantém girando em sua órbita desde os maiores planetas até pequenas partículas de detritos. No interior do Sol são produzidas enormes quantidades de energia, através de reações de fusão do hidrogênio em hélio. Essa intensa energia é a nossa fonte de luz e calor e sem ela não existiria vida na Terra. É uma estrela anã amarela e sua idade é de cerca de 4,6 bilhões de anos. Estima-se que levará em torno de 6,5 bilhões de anos até se transformar em uma anã branca.", ilustrativo: "Sol"),
Projeto(titulo: "Sol", informacao: "A superfície do sol tem a temperatura de 5,5 mil graus Celsius, seu campo gravitacional é fortíssimo, as interações entre o Sol e a Terra produzem as estações do ano, o tempo, o clima e as correntes oceânicas terrestres, bem como todos os fenômenos semelhantes que ocorrem nos demais corpos celestes do Sistema Solar, demorando cerca de oito minutos para a luz solar chegar à Terra. O sol não possui uma superfície sólida ele é formado por gases, sendo que em número de partículas, a sua composição corresponde a 71% de hidrogênio e 27% de hélio. ", ilustrativo: "Sol"),
Projeto(titulo: "Sol", informacao: "O Sol apresenta seis regiões: 1.Núcleo - parte mais quente e com maior quantidade de massa do Sol. Tem cerca de 139 mil quilômetros. É na região do núcleo que é produzida a energia solar. 2.Zona de radiação - nessa zona, a energia do núcleo propaga-se através da radiação. 3.Zona de convecção - é a porção do Sol onde ocorrem as correntes de convecção de calor. Essas correntes levam a energia para a parte externa da superfície solar. 4.Fotosfera - é a parte visível a Terra.", ilustrativo: "Sol"),
Projeto(titulo: "Sol", informacao: "5.Cromosfera: é a parte onde ocorre a transição entre a fotosfera e a coroa do Sol. 6.Coroa - é constituída por plasma. É a parte luminosa do Sol. Nessa região, a temperatura atinge 2 milhões de graus Celsius. As reações de fusão termonucleares que ocorrem no interior do Sol, produzem uma enorme quantidade de energia. Essa energia é levada para fora pela zona de convecção. Esse escape ocorre com a explosão de gigantes bolhas de plasma quente compostas por átomos ionizados que se movem para cima. A superfície solar, a fotosfera, é composta por cerca de 500 quilômetros de espessura.", ilustrativo: "Sol"),
Projeto(titulo: "Sol", informacao: "Curiosidades: A maior e mais brilhante estrela de nosso Sistema Solar inspirou e influenciou culturas por todo o mundo. Povos antigos, como egípcios, astecas, incas, maias e outros, reverenciaram os movimentos do Sol e da Lua e os registraram em rochas e monumentos. Calendários e monitoramentos de estações foram elaborados com base no movimento da luz solar. O nome Sol era usado pelos romanos, os gregos o chamavam Hélios. A sombra projetada pela Lua, que atinge algum ponto da superfície do planeta Terra, é que determina o desaparecimento do Sol. Tipos de eclipse é classificado da seguinte forma:", ilustrativo: "Sol"),
Projeto(titulo: "Sol", informacao: "1-Eclipse Total: ocorre quando o Sol fica totalmente encoberto pela Lua, bloqueando toda a luz solar. Um eclipse total do Sol demora cerca de 400 anos para se repetir num mesmo lugar do planeta Terra. 2-Eclipse Parcial: ocorre quando apenas uma parte do Sol fica encoberta pela Lua, bloqueando parcialmente a luminosidade do Sol. 3-Eclipse Anular ou Anelar: ocorre porque o diâmetro angular da Lua é menor que o diâmetro do Sol, de forma que o satélite (Lua) consegue cobrir apenas o centro do disco solar, formando um anel brilhante.", ilustrativo: "Sol"),
        
        //Mercurio
Projeto(titulo: "Mercurio", informacao: "Mercúrio é o primeiro planeta do sistema solar, Mercúrio é o menor planeta do Sistema Solar e o mais próximo do Sol, distando-se em apenas 57,9 milhões de quilômetros da estrela em média. Com um diâmetro de 4878 km, é o menor entre os planetas do nosso sistema solar e também o que realiza mais rapidamente o seu movimento de translação, executado a uma velocidade de aproximadamente 47,87 km/s, levando, assim, 88 dias para completar sua volta ao redor do sol.", ilustrativo: "Mercurio"),
Projeto(titulo: "Mercurio", informacao: "Quanto ao movimento de rotação, o planeta Mercúrio executa-o apenas três vezes durante duas órbitas de translação, o que faz com que o seu dia solar seja o equivalente a 173 dias terrestres. Além disso, esse movimento de rotação acontece com o seu eixo perpendicular ao plano da órbita, por isso, não apresenta estações do ano e alguns locais não recebem a luz do sol. A atmosfera de Mercúrio é basicamente composta por átomos de árgon, néon e hélio e apresenta uma pressão muito baixa, cerca de um bilhão de vezes menor do que a da Terra.", ilustrativo: "Mercurio"),
Projeto(titulo: "Mercurio", informacao: "As altas temperaturas, em razão da proximidade com o sol, fazem com que esses átomos se dispersem pelo espaço, o que tem como consequências: o pequeno índice de erosão hídrica e eólica; a baixa proteção da atmosfera frente a meteoritos e a incapacidade de se conservar as médias térmicas. Por conta desse último fator, as temperaturas no planeta Mercúrio variam entre 430ºC e -170ºC durante a noite. A superfície de Mercúrio é relativamente semelhante à da Lua, com uma grande quantidade de crateras formadas pelo impacto dos meteoritos que atingiram o planeta.", ilustrativo: "Mercurio"),
Projeto(titulo: "Mercurio", informacao: "A ausência de agentes erosivos de transformação do relevo faz com que essas crateras permaneçam conservadas durante muito tempo. A maior delas é a Bacia Caloris, formada há milhares de anos e com um diâmetro de 1550 km de extensão. O planeta Mercúrio recebe esse nome em virtude do seu acelerado movimento de translação, o que faz com que ele se mova mais rapidamente no céu do que os demais corpos celestes visíveis. Na mitologia romana, Mercúrio era o mensageiro dos deuses por ser o mais rápido entre todos os seres do mundo.", ilustrativo: "Mercurio"),
Projeto(titulo: "Mercurio", informacao: "Graças à sua proximidade com o sol, é muito difícil observar Mercúrio, o que só é possível próximo ao nascer do sol e logo após o entardecer. A maioria das informações é proveniente da sonda Mariner 10, enviada em 1973, e da sonda Messenger, enviada pela Agência Espacial Americana (NASA) em 2008. Recentemente, foi lançada pela Agência Espacial Europeia (ESA) e pela Agência Japonesa de Exploração Aerospacial (JAXA) a sonda Bepicolombo, que concluirá o mapeamento da superfície do planeta e fornecerá novos dados e informações.", ilustrativo: "Mercurio"),
Projeto(titulo: "Mercurio", informacao: "Vida em Mercurio? A proximidade de Mercúrio com o Sol (é o planeta mais próximo dessa estrela) torna o desenvolvimento da vida nesse planeta bastante difícil, pois há altas e baixas temperaturas, instabilidades climáticas, atmosfera fraca e uma superfície escura, talvez devido à presença de grafite ou mesmo pelas altas temperaturas, que “carbonizam” as paisagens.", ilustrativo: "Mercurio"),
        
        //Venus
Projeto(titulo: "Vênus", informacao: "Vênus é um planeta do sistema solar, localiza-se no segundo lugar a partir do sol, além disso, é o sexto maior entre todos os outros planetas. Vênus possui tamanho e massa semelhante a do planeta Terra, por isso os planetas citados eram considerados gêmeos, no entanto, as características parecidas se limitam à proporção corporal. Salvo esse ponto apresentado, os dois planetas são totalmente distintos, uma vez que Vênus não oferece condições para proliferação de vida. Vênus não possui luas", ilustrativo: "Venus"),
Projeto(titulo: "Vênus", informacao: "Em Vênus a atmosfera é muito compacta, formada por uma enorme quantidade de gás carbônico, por ser muito densa desenvolve um elevado efeito estufa que faz o planeta produzir altíssimas temperaturas. Onde os raios solares incidem de forma perpendicular na superfície do planeta as temperaturas atingem até 460ºC. Outra particularidade do planeta Vênus é quanto aos movimentos de rotação e translação. Para a realização total do primeiro movimento são necessários 243 dias (referente aos dias terrestres) e no segundo, 224 dias, dessa forma um ano em Vênus é menor que 1 dia.", ilustrativo: "Venus"),
Projeto(titulo: "Vênus", informacao: "Viagens tripuladas a Marte são ambições de programas de agências espaciais e empresas privadas. A missão Artemis, da Nasa, planeja enviar astronautas ao planeta vermelho até 2028. Já Elon Musk, CEO da SpaceX, manifestou planos de ocupar o solo marciano até 2050. Para alguns cientistas, no entanto, antes de pousar em solo marciano, as missões devem considerar passagens por Vênus. Em estudo publicado em formato pré-print, que ainda será submetido a revisão de pares na revista Acta Astronautic, pesquisadores argumentam que sobrevoos na órbita de Vênus podem tornar missões com destino a Marte mais rápidas e baratas.", ilustrativo: "Venus"),
Projeto(titulo: "Vênus", informacao: "Já a segunda opção corresponde ao que o estudo chama de “missão de oposição”. Neste caso, as espaçonaves passariam por Vênus para aproveitar a força gravitacional do planeta e, então, ajustar o percurso até Marte. Segundo os cientistas, isso ajudaria significativamente a reduzir a demanda de energia das missões, economizaria combustível, liberaria espaço nas espaçonaves e reduziria custos. Outra vantagem, dizem os pesquisadores, remete à periodicidade das missões. Viagens com passagem em Vênus poderiam partir da Terra a cada 19 meses.", ilustrativo: "Venus"),
Projeto(titulo: "Vênus", informacao: "Para os cientistas, o trajeto proposto no estudo ainda seria útil para explorar Vênus e coletar informações ainda mais precisas sobre o planeta. Há ciência em dois planetas por muito menos do que o preço de duas missões tripuladas separadas, disse ao Space.com, Paul Byrne, coautor do estudo e geólogo planetário da Universidade Estadual da Carolina do Norte.  Os autores ressaltam que sondas espaciais operadas em bases na Terra já coletam informações sobre o segundo planeta do sistema solar. Os sobrevoos na órbita de Vênus, no entanto, permitiria aos astronautas mais possibilidades de operação dos dispositivos localizados na superfície.", ilustrativo: "Venus"),
Projeto(titulo: "Vênus", informacao: "No nosso Sistema Solar, os planetas são divididos entre gasosos e rochosos. Os primeiros tendem a ter vários satélites. Já os rochosos possuem poucos ou nenhum: Marte é orbitado por dois satélites e a Terra por apenas um; Mercúrio e Vênus não possuem luas.", ilustrativo: "Venus"),
        
        //Terra
Projeto(titulo: "Terra", informacao: "O Planeta Terra é o terceiro dos oito planetas que fazem parte do Sistema Solar. A partir do Sol: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno. Também chamado de Planeta Azul, recebe essa denominação posto que grande parte do planeta é formado por água. O movimento de rotação da Terra dura 23 horas, 56 minutos e 04 segundos e o ano terrestre é de aproximadamente 365 dias e 6 horas. A temperatura média da Terra é de 14ºC.", ilustrativo: "Terra"),
Projeto(titulo: "Terra", informacao: "Segundo os estudos, a Terra se formou há 4,56 bilhões de anos. Inicialmente, o planeta chamado de Proto-Terra sofria com diversas colisões de outros astros que vagavam pelo universo, como a Terra. Uma dessas colisões teria sido a responsável pela formação da Lua. Nesse primeiro momento, a Terra encontrava-se envolta em gás e com uma intensa atividade vulcânica. Ao longo de todo um processo de resfriamento, tornou-se possível a formação da crosta terrestre.", ilustrativo: "Terra"),
Projeto(titulo: "Terra", informacao: "O arrefecimento do novo planeta tornou possível a presença de água em estado líquido e, consequentemente, a formação dos oceanos. Desse modo, concluiu-se o processo de formação do planeta Terra, há 4 bilhões de anos. Algumas centenas de milhões de anos após essa forma, tem início a vida, a partir, dá abiogênese química oriunda da radioatividade e das condições atmosféricas. Surgem as primeiras células procariontes e, posteriormente as algas anaeróbicas que produziram o oxigênio presente na atmosfera. O oxigênio foi responsável pelo surgimento dos demais seres vivos dentro de todo um processo evolutivo da vida no planeta.", ilustrativo: "Terra"),
Projeto(titulo: "Terra", informacao: "É o único planeta do Sistema Solar em que existe água em estado líquido, característica que junto ao oxigênio e a temperatura média de 14ºC tornam possível a vida no planeta. Essa água corresponde cerca de 70% da superfície do planeta, local chamado de hidrosfera. A Terra é composta de diversos gases, de forma que em sua atmosfera encontramos principalmente, o nitrogênio (78%) e oxigênio (21%). O formato da Terra, assim como de todos os planetas, tende a ser esférico por conta de seu centro gravitacional.", ilustrativo: "Terra"),
Projeto(titulo: "Terra", informacao: "Entretanto, rigorosamente, o planeta não é perfeitamente esférico, aproxima-se seu formato é chamado de geoide. O geoide é uma aproximação matemática criada pela impossibilidade de calcular a superfície terrestre por conta de sua irregularidade. A superfície terrestre varia entre os cerca de 8850 metros de altura do pico do Monte Everest e os 11000 metros negativos da Fossa das Marianas no Oceano Pacífico. Outro fator que contraria uma condição esférica da Terra é o ligeiro achatamento de seus polos, ocasionados por três fatores:", ilustrativo: "Terra"),
Projeto(titulo: "Terra", informacao: "[1].Movimento de rotação que desloca a massa para o Equador Terrestre. [2].Efeito da lua que atua sobre as marés, mas também sobre a matéria sólida do planeta. [3].Efeito do centro gravitacional do planeta, que exerce uma força maior sobre os polos achatados.", ilustrativo: "Terra"),

        //Marte
Projeto(titulo: "Marte", informacao: "Marte é o segundo menor planeta do sistema solar e o quarto planeta mais próximo do Sol e o segundo menor planeta do sistema solar, depois de Mercúrio, sendo consideravelmente menor que o planeta Terra. Apresenta uma coloração avermelhada, pela presença de óxido de ferro na sua superfície. Por isso, recebeu o nome de Marte, em homenagem ao deus romano da guerra. Possui duas pequenas luas de formato irregular: Fobos (medo) e Deimos (pânico). Seus nomes derivam da mitologia grega e representam os filhos de Ares (Marte) e Afrodite (Vênus).", ilustrativo: "Marte"),
Projeto(titulo: "Marte", informacao: "Marte é um dos planetas mais estudados do sistema solar. Podendo ser visto da Terra a olho nu, ou seja, sem auxílio de um telescópio. A duração do dia em Marte aproxima-se do planeta Terra, com 24 horas e 37 minutos, embora o ano marciano tenha duração de 687 dias terrestres ele é muito frio, árido e rochoso. A sua temperatura máxima é de aproximadamente 25°C, com uma média de -60°C, a qual pode chegar até cerca de -140°C durante à noite.", ilustrativo: "Marte"),
Projeto(titulo: "Marte", informacao: "Sendo um planeta terrestre (rochoso), suas camadas são compostas por atmosfera, crosta, manto e núcleo. A maioria das rochas na superfície é formada por basalto. Sua atmosfera é muito fina e é composta essencialmente de gás carbônico, embora exista em menor quantidade o nitrogênio, oxigênio, argônio, dentre outros gases. Quarto planeta do sistema solar, sua distância média ao Sol é de 228 milhões de km. Possui dois satélites naturais, que são as duas luas de Marte. Esses satélites foram descobertos em 1877 e muitos cientistas acreditam que podem ter sido asteroides capturados pela gravidade de Marte.", ilustrativo: "Marte"),
Projeto(titulo: "Marte", informacao: "Vida em Marte? Conhecido desde a antiguidade, a partir do século XIX Marte tem despertado maior atenção entre astrônomos e cientistas. Uma vez que o planeta vermelho se assemelha à Terra em diversos aspectos, tal como as estações do ano, relevo (vales, dunas, planícies, planaltos, cânions, etc.) e aproximação do dia terrestre (quase 24 h), há pesquisas que apostam na existência de vida no planeta. No entanto, o fato de ser envolvido numa atmosfera fina e bastante rarefeita reforça a impossibilidade de condições de vida no planeta.", ilustrativo: "Marte"),
Projeto(titulo: "Marte", informacao: "O que despertou ainda mais o interesse dos cientistas na atualidade foi um estudo realizado no ano 2000 pela NASA (Administração Nacional da Aeronáutica e do Espaço). Nesse estudo, foi confirmada a existência de processos erosivos no planeta, o que evoca a possibilidade da existência de água e, consequentemente, de vida em Marte. Embora tenham descoberto esses indícios, ainda não ficou comprovada a existência de outros seres no planeta. No entanto, isso não exclui a possibilidade de o mesmo ter sido habitado num passado remoto.", ilustrativo: "Marte"),
Projeto(titulo: "Marte", informacao: "Pouco se conhece de Marte, mas a ambição é fazer do planeta uma ‘segunda casa’ para os humanos. Pelo menos os planos mostram que o planeta vermelho poderá ser importante para a expansão espacial dos terráqueos. Assim, o planeta está sendo estudado e com cada vez mais tecnologias. Hoje sabe-se que o planeta tem duas luas estranhas, mas agora um novo estudo levanta outras questões e afirma que no início essas luas eram a mesma. Tal como a Terra, Marte poderá ter tido apenas uma lua, mas algo esmagou o satélite natural partindo-o nas duas luas que conhecemos hoje.", ilustrativo: "Marte"),
        
        //Jupiter        
Projeto(titulo: "Jupiter", informacao: "Júpiter é o maior planeta do Sistema Solar, o quinto a partir do Sol e o quarto corpo celeste mais brilhante no céu – os demais são o Sol, a Lua e Vênus. A massa é 318 vezes superior à da Terra e maior que todos os planetas do Sistema Solar juntos. Tem cerca de 143 mil quilômetros de diâmetro no equador, o que equivale a 11 vezes mais que o diâmetro da Terra. É orbitado por 67 satélites naturais, situando-se a uma distância média de 778,3 milhões de quilômetros do Sol.", ilustrativo: "Jupiter"),
Projeto(titulo: "Jupiter", informacao: "Foi batizado com esse nome em homenagem ao governante do Olimpo, Júpiter, o deus dos deuses. Júpiter, assim como Saturno, exibe um sistema de anéis, contudo são tênues e menos brilhantes, não observáveis a partir da Terra e que só foram descobertos em 1979 pela sonda Voyager 1. É um dos quatro Gigantes Gasosos, juntamente com Saturno, Urano e Netuno. Gigantes Gasosos são compostos, principalmente pelos gases hidrogênio, hélio e metano e, ainda, um pequeno núcleo sólido no interior.", ilustrativo: "Jupiter"),
Projeto(titulo: "Jupiter", informacao: "A atmosfera de Júpiter é composta por hidrogênio e hélio, tendo, ainda, traços de metano, amônia, vapor d'água e outros componentes a uma temperatura de 103ºC. O planeta, cujo formato é de uma esfera oblata, tem elevada pressão atmosférica e a intensidade provoca a quebra dos átomos hidrogênio, que se transforma em metal. Também são encontrados na atmosfera traços de metano, vapor de água, amoníaco, sílicas, carbono, etano, sulfeto de hidrogênio, néon, oxigênio, fosfina e enxofre. Na parte externa da atmosfera há cristais de amônio congelado e traços de benzeno.", ilustrativo: "Jupiter"),
Projeto(titulo: "Jupiter", informacao: "A atmosfera do planeta é dividida em diversas faixas, em várias latitudes, resultando em turbulência e tempestades. A mais conhecida é a Grande Mancha Vermelha, descoberta no século XVII e cujos ventos chegam a 500 quilômetros por hora. Essa tempestade tem um diâmetro transversal duas vezes maior do que a Terra. Júpiter foi observado a primeira vez por Galileu Galilei, em 1610, quando também foi possível a identificação de quatro de seus 63 satélites, Io, Europa, Ganimedes e Calisto. A primeira sonda a visitar Júpiter foi a Pioneer 10 em 1973.", ilustrativo: "Jupiter"),
Projeto(titulo: "Jupiter", informacao: "Também foram usados como instrumentos de observação as visitas das sondas Pioneer 11, Voyager 1, 2 e Ulisses. A sonda Galileu orbitou Júpiter durante 8 anos, terminando o seu serviço em Setembro de 2003. É ainda observado regularmente pelo Telescópio Espacial Hubble. Demora menos de 10 horas a completar uma rotação sobre si próprio. É o movimento de rotação mais rápido dos planetas do Sistema Solar. Já o movimento de translação ocorre cerca de 11,86 anos terrestres. O núcleo de Júpiter é quente, o interior irradia mais calor que recebe do Sol, mais uma característica dos Planetas Gasosos.", ilustrativo: "Jupiter"),
Projeto(titulo: "Jupiter", informacao: "Bastante diferente dos complexos anéis de Saturno, Júpiter tem anéis compostos por partículas de poeira e que estão dentro do campo magnético do planeta. Os anéis são Halo, Principal e Gossamer. Os principais satélites conhecidos são Métis, Adrástea, Amalteia, Tebe, Io, Europa, Ganimedes, Calisto, Leda, Himalia, Lisitea, Elara, Ananke, Carme, Pasifaé e Sinope de um total de 67.", ilustrativo: "Jupiter"),
        
        //Saturno
Projeto(titulo: "Saturno", informacao: "Saturno é o sexto planeta do Sistema Solar contando-se a partir da distância do sol, sendo mais conhecido pelos anéis. Trata-se do segundo maior planeta desse sistema, atrás apenas de Júpiter, apresentando um diâmetro de 120 536 km, que é cerca de nove vezes maior que o diâmetro equatorial terrestre. O movimento de rotação do planeta Saturno é bastante acelerado, o que reverbera no achatamento de seus polos. No total, o planeta leva cerca de 10 horas e 39 minutos para dar volta, enquanto o seu movimento de translação leva de 29 anos, 167 dias e 6 horas para completar-se.", ilustrativo: "Saturno"),
Projeto(titulo: "Saturno", informacao: "Os anéis de Saturno são formados por vários pequenos anéis separados entre si por algumas fendas, sendo a mais notável delas a Divisão de Cassini, que separa os anéis A e B. A origem desses anéis ainda não foi totalmente provada, havendo várias teorias. É bem possível que eles sejam originários de partículas de luas do planeta que foram atingidas por asteroides e destruídas. A composição desses anéis também não é totalmente conhecida, mas são predominantemente formados por partículas de rochas e gelo. Saturno, como sabemos, é um planeta gasoso, sendo basicamente composto de hidrogênio.", ilustrativo: "Saturno"),
Projeto(titulo: "Saturno", informacao: "Ele possui a peculiaridade de ser menos denso do que a água. Na superfície do planeta, os ventos movem-se muito rapidamente e podem alcançar incríveis 1800 km/h, o que seria quatro vezes mais rápido do que a maioria dos furacões aqui da Terra. A atmosfera de Saturno também é predominantemente composta por hidrogênio (97%), além de gás hélio (3%) e gás metano (0,05%). Além disso, existem nuvens formadas provavelmente por amônia congelada, o que dá um tom branco para a aparência atmosférica, isso sem falar em algumas outras nuvens de outras colorações.", ilustrativo: "Saturno"),
Projeto(titulo: "Saturno", informacao: "O planeta Saturno possui um grande número de satélites naturais, sendo que, até o momento, já foram confirmadas sessenta luas, incluindo Titã, que é o segundo maior satélite do sistema solar. Todas as observações realizadas sobre o planeta saturno foram executadas pelas sondas Pionner XI e Voyager I e II, de forma que toda e qualquer informação específica sobre esse planeta só começou a ser levantada a partir do final da década de 1970. Antes disso, tudo era muito misterioso, o que levava à difusão de várias dúvidas sobre como seria formado esse curioso planeta do sistema solar.", ilustrativo: "Saturno"),
Projeto(titulo: "Saturno", informacao: "De acordo com cientistas do Southwest Research Institute, a lua Enceládo abriga condições perfeitas para abrigar organismos vivos. A descoberta foi publicada na revista Proceedings of the National Academy of Sciences, na segunda-feira (9/22). A constatação ocorreu após os cientistas conseguirem encontrar indícios de que o oceano que a lua abriga está repleto de fósforo. O elemento é um dos cinco necessários para a vida e era o único que os cientistas não haviam, até então, identificado no satélite natural. Os outros quatro hidrogênio, oxigênio, carbono e nitrogênio já haviam sido encontrados.", ilustrativo: "Saturno"),
Projeto(titulo: "Saturno", informacao: "A partir de dados obtidos pela missão Cassini-Huygens, que lançou um satélite que orbitou Saturno e as luas dele por mais de 19 anos, haviamos identificado, nas plumas que envolve Enceládo, a presença de gelos de amônia e metano, o que indica nitrogênio e carbono vindo do oceano da lua. Hidrogênio molecular também haviam sido identificados. Nos anos desde, visitou o sistema de Saturno, ficamos repetidamente impressionados com as descobertas possibilitadas pelos dados coletados. O que aprendemos é que a pluma contém quase todos os requisitos básicos da vida como a conhecemos, explicou Christopher R. Glein, autor sênior do estudo.", ilustrativo: "Saturno"),
        
        //Urano
Projeto(titulo: "Urano", informacao: "Urano é o sétimo planeta a partir do Sol, o terceiro maior do Sistema Solar e foi o primeiro a ser encontrado por meio de um telescópio, pelo astrônomo William Herschel em 1781. Demora 84 anos terrestres para completar uma rotação ao sol. Urano é o nome do deus grego do céu. Assim como Vênus, Urano gira de leste a oeste. Observações mais detalhadas do planeta foram realizadas pela sonda Voyager. Juntamente com Netuno, é um dos dois gigantes de gelo do céu. É formado, principalmente, por hidrogénio e hélio, sendo classificado também como planeta gasoso.", ilustrativo: "Urano"),
Projeto(titulo: "Urano", informacao: "A velocidade da órbita de Urano é de 27,4 mil quilômetros por hora e a massa é 14,5 vezes maior que a da Terra. A atmosfera de Urano é constituída, principalmente, de hidrogênio, hélio e metano. A temperatura na superfície chega a 216ºC negativos. A cor azulada resulta da absorção de luz vermelha do metano nas camadas superiores da atmosfera.", ilustrativo: "Urano"),
Projeto(titulo: "Urano", informacao: "O planeta Urano exibe 13 anéis. As observações mais evidentes dos anéis de Urano ocorreram em 1977, por equipes do Airborne Observatory Kuiper e do Observatório de Perth, da Austrália. Na ocasião, foram descobertos cinco anéis, denominados Alpha, Beta, Gamma, Delta e Epsilon, considerando a ordem crescente de distância do planeta pelos pesquisadores do Airborne Observatory. Já a equipe de Perth identificou seis mergulhos distintos na luz das estrelas, que eles chamaram anéis de 1 a 6. Após as observações da Voyager 2, em 1986, foram descobertos mais dois anéis.", ilustrativo: "Urano"),
Projeto(titulo: "Urano", informacao: "Os anéis estão localizados na parte interna das órbitas dos satélites, têm muitas divisões, são opacos e estreitos. A composição dos conjuntos de anéis de Urano não é conhecida, mas assim como os de Saturno, seriam formados por gelo e partículas escuras que não refletem luz. A formação teria ocorrido por choques de satélites, mas não há dados conclusos. O planeta possui 27 luas conhecidas que são nomeadas com personagens das obras de William Shakespeare ou Alexander Pope. As primeiras quatro luas, Titania, Oberon, Ariel e Umbriel foram descobertas entre 1787-1851. A mais complexa de todas, Miranda, foi descoberta em 1948.", ilustrativo: "Urano"),
Projeto(titulo: "Urano", informacao: "Miranda (Urano V) foi descoberto em 1948 por Gerard Kuiper com um telescópio de 2 metros no Observatório McDonald. O hemisfério sul de Miranda foi fotografada pela Voyager 2 em Janeiro de 1986. Sua órbita é prograde (sentido anti-horário) e quase circular (excentricidade = 0,0013). Miranda é feita de uma mistura aproximadamente igual de gelo e rocha. É o mais próxima luas de Urano, o semi-eixo maior de sua órbita é de 129 900 km. Urano é praticamente deitada no plano elíptico com inclinação do seu eixo de rotação de 97,86°.", ilustrativo: "Urano"),
Projeto(titulo: "Urano", informacao: "Miranda mostra uma única variedade de terreno que levou alguns astrônomos acreditam que ele foi quebrado cinco vezes durante sua evolução como mostra o famoso chevron recurso, o brilhante em forma de V logo acima do centro. Esta imagem composta de alta resolução Miranda mostra uma série de picos, vales e superfícies lisas, bem como canyons obscuros de profundidade ≈ 24 km, como a grande cratera", ilustrativo: "Urano"),
        
        //Neturno
Projeto(titulo: "Neturno", informacao: "Netuno é o oitavo planeta a partir do Sol. É um gigante gasoso, bem como Júpiter, Saturno e Urano. Está distante 4,5 bilhões de quilômetros do Sol e demora 156 anos terrestres para completar uma órbita. Foi descoberto em 1846 e recebeu o nome do deus romano do mar. A comunidade científica denomina os planetas com nomes da mitologia greco-romana. O planeta demora 16 horas terrestres para completar o movimento de rotação duração de um dia neptuniano. Possui 13 luas confirmadas e uma ainda aguarda a confirmação por cientistas.", ilustrativo: "Neturno"),
Projeto(titulo: "Neturno", informacao: "O planeta Netuno é composto, principalmente, de água muito quente, amônia e metano em seu núcleo, que tem aproximadamente o tamanho da Terra. A atmosfera é formada por hidrogênio, hélio e metano. Assim como Urano, a cor azulada brilhante de Netuno resulta da elevada quantidade de metano na atmosfera. Por conta das peculiaridades do núcleo e atmosfera, Netuno também é chamado de gigante de gelo. Foi observado a primeira vez em 1612 por Galileu Galilei, mas sua descoberta só foi confirmada em 1845 pelas pesquisas de Johann Gottfried Galle, no Observatório de Berlim.", ilustrativo: "Neturno"),
Projeto(titulo: "Neturno", informacao: "A sua principal lua, Tritão, foi descoberta 17 dias depois. Desde que foi descoberto, a primeira volta ao Sol de Netuno ocorreu em 2011. O planeta é invisível a olho nu por causa de sua extrema distância da Terra. O campo magnético de Netuno é cerca de 27 vezes mais potente que o da Terra. Netuno tem seis anéis conhecidos, todos localizados após as observações da sonda Voyager 2. Os anéis são não uniformes, mas têm quatro grossos Regiões (massas de poeira) chamado arcos e seriam jovens, com poucos bilhões de anos. Somente em 1984, astrônomos encontraram evidências da existência do sistema de anéis em torno de Netuno.", ilustrativo: "Neturno"),
Projeto(titulo: "Neturno", informacao: "O conjunto é formado por três anéis proeminentes, denominados Liberdade, Igualdade e Fraternidade. Mais fracos, também foram descobertos os anéis, Adams, Leverrier, Galle e Arago, cuja extensão varia de 42 mil quilômetros a 62 mil quilômetros. As 13 luas de Netuno são nomeadas após vários deuses do mar e ninfas na mitologia grega. Uma última foi descoberta em 2013 pelas observações da sonda Voyager 2 e ainda é aguardado o reconhecimento. Esse corpo celeste orbita em um dos anéis de Netuno.", ilustrativo: "Neturno"),
Projeto(titulo: "Neturno", informacao: "A principal lua de Netuno, Tritão, foi descoberta pelo matemático inglês William Lassell, que era um astrônomo amador. A descoberta ocorreu em 10 de outubro de 1846, mas somente em 1989, a sonda Voyager 2 visitou o planeta e descobriu os fracos anéis a orbitar Netuno. As demais luas foram descobertas entre 2002 e 2003 e todas recebem os nomes de deuses e ninfas da mitologia grega.", ilustrativo: "Neturno"),
Projeto(titulo: "Neturno", informacao: "Tritão é um corpo celeste peculiar e considerado excêntrico, porque orbita no sentido contrário do planeta principal. As observações da Voyager 2 permitiram identificar que a superfície de Tritão é semelhante a uma casca de melão com muitos vulcões de gelo a emitirem nitrogênio líquido, metano e poeira que congelam instantaneamente, transformam-se em neve e retornam à superfície. É um dos objetos mais frios do sistema solar, com 240ºC negativos.", ilustrativo: "Neturno"),
        
        //Os extras entraram logo logo, na primeira atualização
        //Extra: Plutão
Projeto(titulo: "Plutão", informacao: "Plutão é um planeta anão do sistema solar, sendo um dos astros mais distantes do sol e um dos menos influenciados por ele, com uma distância equivalente a cerca de 6 bilhões de anos dessa estrela. Assim, para completar uma volta completa ao redor do sol, Plutão leva 248 vezes mais tempo do que a Terra, o que faz com que a duração de um ano lá seja equivalente a 248 anos terrestres. Muitos acontecimentos relativamente recentes colocaram as características de Plutão em evidência diante das descobertas e mudanças de concepções ao seu respeito.", ilustrativo: "Pluto"),
Projeto(titulo: "Plutão", informacao: "Descoberto em 1930 pelo astrônomo estadunidense Clyde Tombaugh, Plutão era considerado um planeta até o ano de 2006, quando foi reclassificado como um planeta anão. Isso aconteceu porque Plutão não atende a todos os critérios definidos pela União Astronômica Internacional para definir um corpo celeste como planeta, principalmente o fato de ter a sua órbita influenciada por outros planetas. Outro fator que colocou o planeta anão como centro de debates entre cientistas e até entre leigos foi a chegada, em julho de 2015, da sonda New Horizons, enviada pela Nasa no ano de 2007.", ilustrativo: "Pluto"),
Projeto(titulo: "Plutão", informacao: "Com essa missão não tripulada, foi possível obter imagens mais nítidas e informações mais precisas acerca de Plutão e suas cinco luas: Caronte (a maior delas), Nix, Hidra, Estige e Cérbero. Essas duas últimas, inclusive, foram descobertas pela própria sonda nos anos de 2011 e 2012 à medida em que se aproximava de seu destino. Em razão da distância elevada de Plutão, muitas das informações não eram precisas e muitas noções haviam sido obtidas com base em estimativas e hipóteses. Por isso, muitas surpresas foram reveladas com a chegada da New Horizons ao planeta anão.", ilustrativo: "Pluto"),
Projeto(titulo: "Plutão", informacao: "Uma delas foi o fato de o planeta não apresentar um cor azulada como se pensava anteriormente, mas sim um tom alaranjado com manchas marrons. Outra revelação foi o tamanho de plutão, maior do que se calculava, com 2700 km de diâmetro (imaginava-se o valor de 2200 km), o que o torna o maior entre os planetas anões do sistema solar, apresentando 30 km de vantagem sobre Éris. Uma descoberta importante foi sobre o relevo de Plutão, que possui poucas crateras, o que indica uma superfície jovem, com cerca de 100 milhões de anos.", ilustrativo: "Pluto"),
Projeto(titulo: "Plutão", informacao: "O que se especula é que ela tenha sido remodelada ao longo das últimas eras geológicas, provavelmente por erupções vulcânicas. Além disso, observou-se a presença de grandiosas cadeias montanhosas, formadas basicamente por gelo, haja vista que as baixíssimas temperaturas do planeta anão cerca de -248ºC fazem com que o gelo comporte-se como rocha. Diante dessas e de outras informações que vão, aos poucos, sendo obtidas, analisadas e divulgadas pela NASA, é possível esclarecer cada vez mais os mistérios que envolvem Plutão. ", ilustrativo: "Pluto"),
Projeto(titulo: "Plutão", informacao: "Oque é um Planeta anão? Planetas anões são corpos celestes que orbitam uma estrela. No nosso Sistema Solar, o planeta anão mais conhecido é Plutão, rebaixado em 2006 após a revisão das definições de planeta realizadas pela União Astronômica Internacional. A entidade estabelece que um planeta anão é um corpo celeste que orbita o sol, tem massa suficiente para assumir uma forma quase redonda e não é uma lua. Em geral, planetas anões são menores que Mercúrio.", ilustrativo: "Pluto"),
        
        //Extra: Buraco Negro    
Projeto(titulo: "Buraco Negro", informacao: "De forma simplificada, buraco negro é uma região do espaço que possui uma quantidade tão grande de massa concentrada que nada consegue escapar da atração de sua força de gravidade, nem mesmo a luz, e é por isso que são chamados de buracos negros. Até hoje a melhor teoria para explicar este tipo de fenômeno é a Teoria Geral da Relatividade, formulada por Albert Einstein. Mas, para entender melhor do que se trata um buraco negro é preciso entender alguns conceitos.", ilustrativo: "Buraco Negro"),
Projeto(titulo: "Buraco Negro", informacao: "Segundo a teoria de Einstein, a força da gravidade seria uma manifestação da deformação no espaço-tempo causada pela massa dos corpos celestes, como os planetas ou estrelas. Essa deformação seria maior ou menor de acordo com a massa ou a densidade do corpo. Portanto, quanto maior a massa do corpo, maior a deformação e, por sua vez, maior a força de gravidade dele. Consequentemente, maior é a velocidade de escape, força mínima que deve ser empregada, para que um objeto possa vencer a gravidade deste corpo. ", ilustrativo: "Buraco Negro"),
Projeto(titulo: "Buraco Negro", informacao: "É isso que acontece nos buracos negros. Há uma concentração de massa tão grande em um ponto tão infinitamente pequeno que a densidade é suficiente para causar tal deformação no espaço-tempo que a velocidade de escape neste local é maior que a da luz. Por isso que nem mesmo a luz consegue escapar de um buraco negro. E, já que nada consegue se mover mais rápido que a velocidade da luz, nada pode escapar de um buraco negro.", ilustrativo: "Buraco Negro"),
Projeto(titulo: "Buraco Negro", informacao: "Esses tais buracos negros seriam estrelas em seu último estágio de evolução, quando, depois de consumir todo seu combustível, a estrela com massa maior que 3 massas solares, se transformam em uma supernova com um “caroço” no centro. Se a massa deste caroço, que pode ou não se formar, for maior que 2 massas solares ele cai sobre si mesmo, transformando-se em um buraco negro.", ilustrativo: "Buraco Negro"),
Projeto(titulo: "Buraco Negro", informacao: "Às vezes acontece da estrela evoluir no que chamamos de “sistema binário fechado” quando duas estrelas ficam muito próximas e há transferência de matéria de uma para outra, podendo fazer com que uma delas acumule matéria em excesso provocando sua explosão em uma supernova. Nestes casos, o mais provável é que ela evolua para uma estrela de nêutrons, quando elétrons e prótons se fundem em nêutrons. Mas, acontece que em alguns sistemas a concentração de massa é muito grande e ocorre a formação de um buraco negro que continua sugando a massa daquela outra estrela maior.", ilustrativo: "Buraco Negro"),
Projeto(titulo: "Buraco Negro", informacao: "Em abril de 2019, a NASA divulgou a primeira imagem de um buraco negro. Foram utilizados dezenas de radiotelescópios em terra e no espaço para capturar ondas eletromagnéticas vindas de uma galáxia a mais de 55 milhões de anoz-luz de nosso planeta. Utilizando supercomputadores, os dados foram processados e unidos de forma a gerar a imagem abaixo. Ao redor do buraco negro", ilustrativo: "Buraco Negro"),
        
        //Extra:Lua
Projeto(titulo: "Lua", informacao: "A Lua é o único satélite natural da Terra. Os estudos a seu respeito começaram há centenas de anos, enquanto as primeiras viagens bem-sucedidas até ela datam dos anos 1950. A Lua é o único satélite natural da Terra e o quinto maior do Sistema Solar. Ela se formou, há aproximadamente 4,5 bilhões de anos, do impacto de um grande corpo celeste com o planeta, e desde então realiza a sua órbita ao redor dele e também do Sol. A forma como a luz solar.", ilustrativo: "Lua2"),
Projeto(titulo: "Lua", informacao: "A Lua é o único satélite natural da Terra. Está a 384.400 km do planeta, e a cada ano se afasta 3,78 centímetros. Sua superfície está repleta de crateras de impacto, fragmentos de rocha e poeira. Crateras preenchidas com lava no passado deram origem a pequenas elevações (marias) nela. Formou-se, há 4,5 bilhões de anos, do impacto de um enorme meteorito na Terra. A forma como enxergamos a sua iluminação da Terra constitui as suas fases. Sua interação com o planeta produz fenômenos como as marés e os eclipses. Estudos revelam aspectos importantes desse astro, como sua composição química.", ilustrativo: "Lua2"),
Projeto(titulo: "Lua", informacao: "A Lua é o único satélite natural do planeta Terra. Esse corpo celeste possui um raio de aproximadamente 1740 km, o que o torna a quinta maior lua de todo o Sistema Solar. A massa da Lua é de 7,35 x 1019 toneladas, valor que corresponde a apenas 1,23% da massa terrestre. Ela está posicionada a uma distância de 384.400 km do nosso planeta, intervalo, pelo menos, 18 vezes maior do que quando ela se formou, há 4,5 bilhões de anos. O processo de distanciamento não cessou, e a cada ano ele aumenta em 3,78 centímetros.", ilustrativo: "Lua2"),
Projeto(titulo: "Lua", informacao: "De acordo com a Nasa, o satélite é detentor de uma camada atmosférica muito fina e frágil chamada de exosfera e que, na verdade, não exerce nenhum tipo de proteção. Em função disso, observa-se em sua superfície uma série de crateras de impacto de meteoritos, além de escombros e camadas e mais camadas de detritos rochosos (regolitos) e pó, desenvolvidos ao longo de sua existência em função dos impactos.", ilustrativo: "Lua2"),
Projeto(titulo: "Lua", informacao: "Existem áreas de relevo elevado na superfície da Lua resultantes do preenchimento das crateras por derrames de lava, e os últimos ocorreram há cerca de 1,2 bilhão de anos. Essas elevações são chamadas de marias. Com relação às temperaturas, a variação é muito grande entre o hemisfério que está recebendo iluminação no momento e o seu oposto. O primeiro, que recebe luz solar, tem temperatura de até 127 ºC, enquanto na face não iluminada pelo Sol a medição é de -173 ºC. Já a força da gravidade experimentada na superfície lunar é de 1,62 m/s², seis vezes menor do que a gravidade terrestre.", ilustrativo: "Lua2"),
Projeto(titulo: "Lua", informacao: "A Lua é uma fonte secundária de luz, o que significa que a iluminação que ela emite é derivada da luz que recebe do Sol. Diferentes hemisférios e partes da Lua estão iluminados em momentos distintos de sua trajetória ao redor do Sol e também do planeta Terra, o que produz as diferentes fases da Lua. A duração aproximada das quatro fases principais é de sete dias, enquanto o tempo que o satélite demora para dar uma volta em torno da Terra é de 27 dias.", ilustrativo: "Lua2")
    ]
    
    func MoverDex(index: Int) -> Projeto{
        return explicar[index]
    }
    
    //Meu Index = Dex
    var Dex = -1
    var TOTAL = 6
    var passandoInfo = 0
    
    func reloadSistem()-> Projeto{
        Dex = Dex + 1
        return explicar[Dex]
    }
    
    func verificarFinal() -> Bool{
        passandoInfo = passandoInfo + 1
        if passandoInfo == TOTAL{
            return true
        }else{
            return false
        }
    }
}
